### PR TITLE
Added tasks 1233, 1234, 1235, 1237, 1238

### PR DESCRIPTION
**Pull request by ThanhNIT**

### CODE REVIEW

**Comment by javadev** [comment]
There are no unit tests for task s1237_find_positive_integer_solution_for_a_given_equation.

**Comment by ThanhNIT** [comment]
> There are no unit tests for task s1237_find_positive_integer_solution_for_a_given_equation.

I don't know how to write unit test for it

**Comment by javadev** [comment]
✅

**Comment by javadev** [comment]
> > There are no unit tests for task s1237_find_positive_integer_solution_for_a_given_equation.
> 
> I don't know how to write unit test for it

I will check other repositories.

**Pull request merged**
