### PR TITLE
Added task 2016

### PR DESCRIPTION
**Pull request by AryamanMishra**

### CODE REVIEW

**Comment by javadev** [comment]
Hi @AryamanMishra ,

Thank you for the task solution.

Please add a unit test.

**Comment by AryamanMishra** [comment]
Sure sir.

**Comment by javadev** [comment]
Please fix code format

https://github.com/javadev/LeetCode-in-Java/runs/6548740523?check_suite_focus=true

**Comment by javadev** [comment]
👍

**Pull request merged**
